"""OS & Linux content module — Operating Systems and Linux interview prep."""

from __future__ import annotations

from generator.models import MCQ, NotebookSpec, TopicSection


def get_os_linux_spec() -> NotebookSpec:
    """Return a complete NotebookSpec for the OS/Linux notebook."""
    return NotebookSpec(
        title="OS & Linux — Interview Prep",
        filename="02_os_linux.ipynb",
        strategy_tips=_strategy_tips(),
        sections=_beginner_sections() + _mid_level_sections(),
        mock_test=_mock_test(),
        cheat_sheet=_cheat_sheet(),
    )


# ---------------------------------------------------------------------------
# Strategy tips
# ---------------------------------------------------------------------------

def _strategy_tips() -> str:
    return (
        "## Strategy Tips for the OS/Linux MCQ Section (25 minutes)\n\n"
        "**Time Allocation:** With 10-12 questions in 25 minutes you have "
        "roughly 2 minutes per question. Don't spend more than 2.5 minutes "
        "on any single question.\n\n"
        "**Elimination Technique:** Read all four options first. Eliminate "
        "answers that are clearly wrong — even removing one option raises "
        "your odds from 25% to 33%.\n\n"
        "**Skip and Return:** If a question involves a command you don't "
        "recognize, skip it and come back. Answer the ones you're confident "
        "about first to lock in points.\n\n"
        "**Command Questions:** Visualize the command running in a terminal. "
        "Think about what flags do and what the expected output format looks "
        "like.\n\n"
        "**Conceptual Questions:** For OS theory (scheduling, memory), "
        "relate the concept to a real-world analogy. For example, Round "
        "Robin scheduling is like taking turns in a game.\n\n"
        "**Common Traps:** Watch for subtle differences between similar "
        "commands (e.g., `netstat` vs `ss`, `chmod 755` vs `chmod 644`). "
        "Pay attention to whether the question asks about the command's "
        "default behavior or a specific flag."
    )


# ---------------------------------------------------------------------------
# Beginner sections
# ---------------------------------------------------------------------------

def _beginner_sections() -> list[TopicSection]:
    return [
        _linux_file_system_hierarchy(),
        _basic_shell_commands(),
        _process_management(),
        _file_permissions_ownership(),
        _package_management(),
    ]


def _linux_file_system_hierarchy() -> TopicSection:
    explanation = (
        "### Linux File System Hierarchy\n\n"
        "Linux organizes files in a single-rooted tree structure starting "
        "at `/`. Every file and directory lives under this root. Understanding "
        "the standard directory layout (defined by the Filesystem Hierarchy "
        "Standard — FHS) is essential for system administration.\n\n"
        "| Directory | Purpose |\n"
        "|-----------|--------|\n"
        "| `/` | Root of the entire filesystem |\n"
        "| `/home` | User home directories (e.g., `/home/alice`) |\n"
        "| `/etc` | System-wide configuration files |\n"
        "| `/var` | Variable data — logs, caches, spool files |\n"
        "| `/tmp` | Temporary files (cleared on reboot on many distros) |\n"
        "| `/usr` | User programs, libraries, documentation |\n"
        "| `/bin` | Essential user command binaries (ls, cp, mv) |\n"
        "| `/sbin` | System administration binaries (fdisk, iptables) |\n"
        "| `/dev` | Device files (disks, terminals, null device) |\n"
        "| `/proc` | Virtual filesystem exposing kernel/process info |\n\n"
        "**Key points:**\n"
        "- `/etc` is where you find config files like `/etc/hosts`, "
        "`/etc/fstab`, `/etc/passwd`.\n"
        "- `/var/log` stores system and application logs.\n"
        "- `/proc` is not on disk — it's generated by the kernel at runtime. "
        "For example, `/proc/cpuinfo` shows CPU details.\n"
        "- `/dev/null` is the \"black hole\" — anything written to it is "
        "discarded."
    )

    examples = [
        (
            "# --- Exploring the filesystem hierarchy ---\n"
            "# List top-level directories\n"
            "import subprocess, textwrap\n\n"
            "# Simulated output of: ls /\n"
            "top_level = textwrap.dedent('''\n"
            "    $ ls /\n"
            "    bin   dev  home  lib    media  opt   root  sbin  sys  usr\n"
            "    boot  etc  init  lib64  mnt    proc  run   srv   tmp  var\n"
            "''')\n"
            "print(top_level)\n\n"
            "# View CPU info from /proc\n"
            "proc_cpuinfo = textwrap.dedent('''\n"
            "    $ cat /proc/cpuinfo | head -5\n"
            "    processor       : 0\n"
            "    vendor_id       : GenuineIntel\n"
            "    cpu family      : 6\n"
            "    model           : 142\n"
            "    model name      : Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz\n"
            "''')\n"
            "print(proc_cpuinfo)\n\n"
            "# Check disk usage of key directories\n"
            "du_output = textwrap.dedent('''\n"
            "    $ du -sh /var/log /etc /tmp\n"
            "    256M    /var/log\n"
            "    12M     /etc\n"
            "    4.0K    /tmp\n"
            "''')\n"
            "print(du_output)"
        ),
    ]

    mcqs = [
        MCQ(
            question="Which directory contains system-wide configuration files on a Linux system?",
            options={
                "A": "/home",
                "B": "/etc",
                "C": "/var",
                "D": "/tmp",
            },
            correct="B",
            explanation=(
                "/etc (\"et cetera\" or \"editable text configuration\") stores "
                "system-wide configuration files such as /etc/hosts, "
                "/etc/fstab, and /etc/passwd."
            ),
            distractors={
                "A": "/home contains user home directories, not system configuration.",
                "C": "/var stores variable data like logs and caches, not config files.",
                "D": "/tmp is for temporary files that may be cleared on reboot.",
            },
            mcq_type="conceptual",
        ),
        MCQ(
            question="What type of filesystem is /proc in Linux?",
            options={
                "A": "A regular ext4 filesystem stored on disk",
                "B": "A virtual filesystem generated by the kernel at runtime",
                "C": "A network filesystem mounted from a remote server",
                "D": "A swap partition used for virtual memory",
            },
            correct="B",
            explanation=(
                "/proc is a virtual (pseudo) filesystem that does not exist "
                "on disk. The kernel generates its contents dynamically to "
                "expose process and system information (e.g., /proc/cpuinfo, "
                "/proc/meminfo)."
            ),
            distractors={
                "A": "/proc is not stored on disk — it's generated in memory by the kernel.",
                "C": "/proc is local to the machine, not a network mount.",
                "D": "Swap partitions are separate from /proc; /proc exposes kernel data.",
            },
            mcq_type="conceptual",
        ),
    ]

    return TopicSection(
        title="Linux File System Hierarchy",
        difficulty="Beginner",
        explanation=explanation,
        examples=examples,
        practice=mcqs,
        key_takeaways=[
            "The root directory `/` is the top of the entire filesystem tree.",
            "`/etc` holds configuration, `/var` holds variable data (logs), `/tmp` holds temporary files.",
            "`/proc` is a virtual filesystem — it exposes kernel and process info without using disk.",
            "`/dev/null` discards all data written to it — useful for suppressing output.",
            "Know the FHS layout — it's a common interview topic for Linux roles.",
        ],
    )


def _basic_shell_commands() -> TopicSection:
    explanation = (
        "### Basic Shell Commands\n\n"
        "The Linux shell is your primary interface for system administration. "
        "Mastering core commands is essential for any SDET role.\n\n"
        "**File listing — `ls`:**\n"
        "- `ls` — list directory contents\n"
        "- `ls -l` — long format (permissions, owner, size, date)\n"
        "- `ls -la` — include hidden files (dotfiles)\n"
        "- `ls -lh` — human-readable sizes\n\n"
        "**Navigation — `cd`:**\n"
        "- `cd /path/to/dir` — change to absolute path\n"
        "- `cd ..` — go up one level\n"
        "- `cd ~` — go to home directory\n"
        "- `cd -` — go to previous directory\n\n"
        "**Text search — `grep`:**\n"
        "- `grep pattern file` — search for pattern in file\n"
        "- `grep -r pattern dir/` — recursive search\n"
        "- `grep -i pattern file` — case-insensitive\n"
        "- `grep -n pattern file` — show line numbers\n\n"
        "**File search — `find`:**\n"
        "- `find /path -name '*.log'` — find by name pattern\n"
        "- `find /path -type f -size +10M` — find files larger than 10MB\n"
        "- `find /path -mtime -7` — modified in last 7 days\n\n"
        "**Permissions — `chmod` and `chown`:**\n"
        "- `chmod 755 script.sh` — set permissions\n"
        "- `chown user:group file` — change ownership"
    )

    examples = [
        (
            "# --- ls: listing files ---\n"
            "# Simulated terminal output\n"
            "import textwrap\n\n"
            "ls_output = textwrap.dedent('''\n"
            "    $ ls -la /home/user/project\n"
            "    total 32\n"
            "    drwxr-xr-x  4 user user 4096 Jan 15 10:30 .\n"
            "    drwxr-xr-x 20 user user 4096 Jan 15 09:00 ..\n"
            "    -rw-r--r--  1 user user  220 Jan 15 10:30 .bashrc\n"
            "    -rwxr-xr-x  1 user user 1024 Jan 15 10:25 deploy.sh\n"
            "    drwxr-xr-x  2 user user 4096 Jan 15 10:20 src\n"
            "    -rw-r--r--  1 user user  512 Jan 15 10:15 README.md\n"
            "''')\n"
            "print(ls_output)"
        ),
        (
            "# --- grep: searching text ---\n"
            "import textwrap\n\n"
            "grep_output = textwrap.dedent('''\n"
            "    $ grep -rn \"ERROR\" /var/log/app/\n"
            "    /var/log/app/server.log:42:2024-01-15 10:30:15 ERROR Connection refused\n"
            "    /var/log/app/server.log:87:2024-01-15 11:45:22 ERROR Timeout exceeded\n"
            "    /var/log/app/worker.log:15:2024-01-15 12:00:01 ERROR Task failed\n\n"
            "    $ grep -c \"ERROR\" /var/log/app/server.log\n"
            "    2\n\n"
            "    # Pipe with grep to filter process list\n"
            "    $ ps aux | grep nginx\n"
            "    root      1234  0.0  0.1  12345  6789 ?  Ss  10:00  0:00 nginx: master\n"
            "    www-data  1235  0.0  0.2  12345  9876 ?  S   10:00  0:01 nginx: worker\n"
            "''')\n"
            "print(grep_output)"
        ),
        (
            "# --- find: locating files ---\n"
            "import textwrap\n\n"
            "find_output = textwrap.dedent('''\n"
            "    # Find all Python files\n"
            "    $ find /home/user/project -name \"*.py\"\n"
            "    /home/user/project/src/main.py\n"
            "    /home/user/project/src/utils.py\n"
            "    /home/user/project/tests/test_main.py\n\n"
            "    # Find files modified in the last 24 hours\n"
            "    $ find /var/log -type f -mtime -1\n"
            "    /var/log/syslog\n"
            "    /var/log/auth.log\n"
            "    /var/log/kern.log\n\n"
            "    # Find and delete .tmp files\n"
            "    $ find /tmp -name \"*.tmp\" -type f -delete\n"
            "''')\n"
            "print(find_output)"
        ),
    ]

    mcqs = [
        MCQ(
            question=(
                "Which command recursively searches for the text \"timeout\" "
                "(case-insensitive) in all files under /var/log?"
            ),
            options={
                "A": "find /var/log -name 'timeout'",
                "B": "grep -ri 'timeout' /var/log",
                "C": "ls -R /var/log | grep timeout",
                "D": "cat /var/log/* | find timeout",
            },
            correct="B",
            explanation=(
                "`grep -ri` performs a recursive (-r) case-insensitive (-i) "
                "search for the pattern 'timeout' in all files under /var/log."
            ),
            distractors={
                "A": "`find -name` searches for filenames, not file contents.",
                "C": "`ls -R | grep` would only match directory/file names, not file contents.",
                "D": "`find` searches for files, not text within files; this syntax is invalid.",
            },
            mcq_type="command",
        ),
        MCQ(
            question=(
                "What does the command `find /home -type f -size +100M` do?"
            ),
            options={
                "A": "Finds directories larger than 100MB under /home",
                "B": "Finds files larger than 100MB under /home",
                "C": "Finds files exactly 100MB in size under /home",
                "D": "Finds the 100 largest files under /home",
            },
            correct="B",
            explanation=(
                "`-type f` restricts to regular files (not directories). "
                "`-size +100M` means greater than 100 megabytes. Together, "
                "this finds all regular files larger than 100MB under /home."
            ),
            distractors={
                "A": "`-type f` specifies files, not directories. Use `-type d` for directories.",
                "C": "`+100M` means greater than 100MB, not exactly. Use `100M` (no +) for exact.",
                "D": "This command doesn't sort or limit results — it finds all matching files.",
            },
            mcq_type="command",
        ),
    ]

    return TopicSection(
        title="Basic Shell Commands",
        difficulty="Beginner",
        explanation=explanation,
        examples=examples,
        practice=mcqs,
        key_takeaways=[
            "`ls -la` shows all files including hidden ones in long format.",
            "`grep -rn` is your go-to for searching text in files recursively with line numbers.",
            "`find` searches by filename, type, size, and modification time — not file contents.",
            "Combine commands with pipes (`|`) for powerful one-liners: `ps aux | grep nginx`.",
            "`cd -` takes you back to the previous directory — a handy shortcut.",
        ],
    )


def _process_management() -> TopicSection:
    explanation = (
        "### Process Management\n\n"
        "A **process** is a running instance of a program. Linux provides "
        "powerful tools to monitor, control, and manage processes.\n\n"
        "**Key commands:**\n"
        "- `ps` — snapshot of current processes\n"
        "- `top` / `htop` — real-time process monitor\n"
        "- `kill` — send signals to processes\n"
        "- `nice` / `renice` — set/change process priority\n"
        "- `bg` / `fg` — move jobs to background/foreground\n\n"
        "**Common signals:**\n"
        "| Signal | Number | Action |\n"
        "|--------|--------|--------|\n"
        "| SIGTERM | 15 | Graceful termination (default for `kill`) |\n"
        "| SIGKILL | 9 | Force kill (cannot be caught or ignored) |\n"
        "| SIGHUP | 1 | Hangup — often used to reload config |\n"
        "| SIGSTOP | 19 | Pause process |\n"
        "| SIGCONT | 18 | Resume paused process |\n\n"
        "**Process states:**\n"
        "- **R** — Running or runnable\n"
        "- **S** — Sleeping (waiting for an event)\n"
        "- **D** — Uninterruptible sleep (usually I/O)\n"
        "- **Z** — Zombie (terminated but not reaped by parent)\n"
        "- **T** — Stopped (by signal or debugger)"
    )

    examples = [
        (
            "# --- ps: viewing processes ---\n"
            "import textwrap\n\n"
            "ps_output = textwrap.dedent('''\n"
            "    $ ps aux | head -10\n"
            "    USER       PID %CPU %MEM    VSZ   RSS TTY  STAT START   TIME COMMAND\n"
            "    root         1  0.0  0.1 169316 11804 ?    Ss   Jan14   0:05 /sbin/init\n"
            "    root         2  0.0  0.0      0     0 ?    S    Jan14   0:00 [kthreadd]\n"
            "    user      1523  0.2  1.5 432100 62340 ?    Sl   10:00   0:15 /usr/bin/python3 app.py\n"
            "    www-data  1890  0.1  0.3  56780 12340 ?    S    10:05   0:02 nginx: worker process\n"
            "    user      2001  0.0  0.1  21456  4320 pts/0 Ss  10:10   0:00 bash\n\n"
            "    # Show only processes for current user\n"
            "    $ ps -u $USER\n"
            "      PID TTY          TIME CMD\n"
            "     1523 ?        00:00:15 python3\n"
            "     2001 pts/0    00:00:00 bash\n"
            "''')\n"
            "print(ps_output)"
        ),
        (
            "# --- kill, nice, bg/fg: controlling processes ---\n"
            "import textwrap\n\n"
            "kill_output = textwrap.dedent('''\n"
            "    # Graceful termination (SIGTERM, default)\n"
            "    $ kill 1523\n\n"
            "    # Force kill (SIGKILL — use as last resort)\n"
            "    $ kill -9 1523\n\n"
            "    # Kill all processes by name\n"
            "    $ killall python3\n\n"
            "    # Start a process with lower priority (higher nice value)\n"
            "    $ nice -n 10 python3 heavy_task.py &\n\n"
            "    # Change priority of running process\n"
            "    $ renice -n 5 -p 1523\n"
            "    1523 (process ID) old priority 0, new priority 5\n\n"
            "    # Background and foreground\n"
            "    $ python3 long_task.py\n"
            "    ^Z                          # Ctrl+Z suspends the process\n"
            "    [1]+  Stopped  python3 long_task.py\n"
            "    $ bg                        # resume in background\n"
            "    [1]+ python3 long_task.py &\n"
            "    $ fg                        # bring back to foreground\n"
            "    python3 long_task.py\n"
            "''')\n"
            "print(kill_output)"
        ),
    ]

    mcqs = [
        MCQ(
            question="What signal does the `kill` command send by default (without specifying a signal)?",
            options={
                "A": "SIGKILL (9)",
                "B": "SIGTERM (15)",
                "C": "SIGHUP (1)",
                "D": "SIGINT (2)",
            },
            correct="B",
            explanation=(
                "By default, `kill <PID>` sends SIGTERM (signal 15), which "
                "requests graceful termination. The process can catch this "
                "signal and clean up before exiting."
            ),
            distractors={
                "A": "SIGKILL (9) must be specified explicitly with `kill -9`. It cannot be caught.",
                "C": "SIGHUP (1) is the hangup signal, typically sent when a terminal closes.",
                "D": "SIGINT (2) is sent by Ctrl+C, not by the default `kill` command.",
            },
            mcq_type="conceptual",
        ),
        MCQ(
            question=(
                "A process shows state 'Z' in the `ps` output. What does this mean?"
            ),
            options={
                "A": "The process is sleeping, waiting for I/O",
                "B": "The process is running on the CPU",
                "C": "The process is a zombie — terminated but not reaped by its parent",
                "D": "The process is stopped by a debugger",
            },
            correct="C",
            explanation=(
                "State 'Z' means zombie. The process has finished execution "
                "but its parent hasn't called wait() to read its exit status. "
                "The process entry remains in the process table until the "
                "parent reaps it."
            ),
            distractors={
                "A": "Sleeping processes show state 'S' (interruptible) or 'D' (uninterruptible).",
                "B": "Running processes show state 'R'.",
                "D": "Stopped processes show state 'T'.",
            },
            mcq_type="conceptual",
        ),
    ]

    return TopicSection(
        title="Process Management",
        difficulty="Beginner",
        explanation=explanation,
        examples=examples,
        practice=mcqs,
        key_takeaways=[
            "`ps aux` shows all running processes; pipe to `grep` to filter.",
            "`kill` sends SIGTERM (15) by default — use `kill -9` only as a last resort.",
            "Zombie processes (state Z) need their parent to call wait() to be cleaned up.",
            "`nice` sets priority at launch; `renice` changes priority of a running process.",
            "Ctrl+Z suspends a process; `bg` resumes it in background; `fg` brings it to foreground.",
        ],
    )


def _file_permissions_ownership() -> TopicSection:
    explanation = (
        "### File Permissions and Ownership\n\n"
        "Linux uses a permission system based on three categories of users "
        "and three types of access:\n\n"
        "**User categories:**\n"
        "- **Owner (u)** — the user who owns the file\n"
        "- **Group (g)** — users in the file's group\n"
        "- **Others (o)** — everyone else\n\n"
        "**Permission types:**\n"
        "- **r (read = 4)** — view file contents / list directory\n"
        "- **w (write = 2)** — modify file / add/remove files in directory\n"
        "- **x (execute = 1)** — run file as program / enter directory\n\n"
        "**Numeric notation:**\n"
        "Each digit is the sum of r(4) + w(2) + x(1):\n"
        "- `755` = rwxr-xr-x (owner: full, group/others: read+execute)\n"
        "- `644` = rw-r--r-- (owner: read+write, group/others: read only)\n"
        "- `700` = rwx------ (owner: full, no access for others)\n\n"
        "**umask:** Sets default permissions for new files. Common default "
        "umask is `022`, meaning new files get `644` and new directories "
        "get `755`.\n\n"
        "**Commands:**\n"
        "- `chmod` — change file permissions\n"
        "- `chown` — change file owner and/or group"
    )

    examples = [
        (
            "# --- chmod and chown examples ---\n"
            "import textwrap\n\n"
            "perm_output = textwrap.dedent('''\n"
            "    # View current permissions\n"
            "    $ ls -l script.sh\n"
            "    -rw-r--r-- 1 user devteam 2048 Jan 15 10:00 script.sh\n\n"
            "    # Make executable (numeric)\n"
            "    $ chmod 755 script.sh\n"
            "    $ ls -l script.sh\n"
            "    -rwxr-xr-x 1 user devteam 2048 Jan 15 10:00 script.sh\n\n"
            "    # Make executable (symbolic)\n"
            "    $ chmod u+x script.sh    # add execute for owner\n"
            "    $ chmod go-w config.txt  # remove write for group and others\n"
            "    $ chmod a+r readme.txt   # add read for all\n\n"
            "    # Change ownership\n"
            "    $ chown alice:devteam project/\n"
            "    $ chown -R alice:devteam project/  # recursive\n\n"
            "    # Check umask\n"
            "    $ umask\n"
            "    0022\n"
            "    # New files: 666 - 022 = 644 (rw-r--r--)\n"
            "    # New dirs:  777 - 022 = 755 (rwxr-xr-x)\n"
            "''')\n"
            "print(perm_output)"
        ),
    ]

    mcqs = [
        MCQ(
            question="What permissions does the numeric mode `644` represent?",
            options={
                "A": "rwxr--r-- (owner: full, group/others: read)",
                "B": "rw-r--r-- (owner: read+write, group/others: read)",
                "C": "rw-rw-r-- (owner/group: read+write, others: read)",
                "D": "r--r--r-- (everyone: read only)",
            },
            correct="B",
            explanation=(
                "6 = r(4)+w(2) = rw-, 4 = r(4) = r--, 4 = r(4) = r--. "
                "So 644 = rw-r--r-- — owner can read and write, group and "
                "others can only read."
            ),
            distractors={
                "A": "rwxr--r-- would be 744 (7 = r+w+x), not 644.",
                "C": "rw-rw-r-- would be 664, not 644.",
                "D": "r--r--r-- would be 444, not 644.",
            },
            mcq_type="conceptual",
        ),
        MCQ(
            question=(
                "What does the command `chmod u+x script.sh` do?"
            ),
            options={
                "A": "Removes execute permission for the owner",
                "B": "Adds execute permission for all users",
                "C": "Adds execute permission for the owner only",
                "D": "Changes the owner of the file",
            },
            correct="C",
            explanation=(
                "`u` refers to the user (owner), `+x` adds execute permission. "
                "So `chmod u+x` adds execute permission for the file owner only. "
                "Group and others are not affected."
            ),
            distractors={
                "A": "The `+` symbol adds permission; `-` would remove it (`u-x`).",
                "B": "To add execute for all users, you'd use `chmod a+x` or `chmod +x`.",
                "D": "`chown` changes ownership, not `chmod`.",
            },
            mcq_type="command",
        ),
    ]

    return TopicSection(
        title="File Permissions and Ownership",
        difficulty="Beginner",
        explanation=explanation,
        examples=examples,
        practice=mcqs,
        key_takeaways=[
            "Permissions are read(4), write(2), execute(1) for owner, group, others.",
            "`755` = rwxr-xr-x is standard for scripts; `644` = rw-r--r-- for regular files.",
            "`chmod` changes permissions; `chown` changes ownership.",
            "umask `022` means new files default to 644 and new directories to 755.",
            "Use symbolic notation (`u+x`) for quick changes, numeric (`755`) for exact settings.",
        ],
    )


def _package_management() -> TopicSection:
    explanation = (
        "### Package Management\n\n"
        "Package managers handle installing, updating, and removing software "
        "on Linux. Different distributions use different package managers:\n\n"
        "**Debian/Ubuntu — `apt` (Advanced Package Tool):**\n"
        "- `apt update` — refresh package index\n"
        "- `apt upgrade` — upgrade all installed packages\n"
        "- `apt install <pkg>` — install a package\n"
        "- `apt remove <pkg>` — remove a package\n"
        "- `apt search <term>` — search for packages\n"
        "- `dpkg -l` — list installed packages\n\n"
        "**RHEL/CentOS — `yum` / `dnf`:**\n"
        "- `yum install <pkg>` / `dnf install <pkg>` — install\n"
        "- `yum update` / `dnf update` — update all packages\n"
        "- `yum remove <pkg>` / `dnf remove <pkg>` — remove\n"
        "- `yum search <term>` / `dnf search <term>` — search\n"
        "- `rpm -qa` — list installed packages\n\n"
        "**Key differences:**\n"
        "- `apt` uses `.deb` packages; `yum`/`dnf` uses `.rpm` packages.\n"
        "- `dnf` is the modern replacement for `yum` on Fedora/RHEL 8+.\n"
        "- Both resolve dependencies automatically."
    )

    examples = [
        (
            "# --- apt: Debian/Ubuntu package management ---\n"
            "import textwrap\n\n"
            "apt_output = textwrap.dedent('''\n"
            "    # Update package index\n"
            "    $ sudo apt update\n"
            "    Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease\n"
            "    Get:2 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]\n"
            "    Reading package lists... Done\n"
            "    15 packages can be upgraded.\n\n"
            "    # Install a package\n"
            "    $ sudo apt install nginx\n"
            "    Reading package lists... Done\n"
            "    The following NEW packages will be installed:\n"
            "      nginx nginx-common nginx-core\n"
            "    0 upgraded, 3 newly installed, 0 to remove.\n"
            "    Do you want to continue? [Y/n] Y\n\n"
            "    # Search for packages\n"
            "    $ apt search python3-pip\n"
            "    python3-pip/jammy 22.0.2+dfsg-1 all\n"
            "      Python package installer\n\n"
            "    # Remove a package\n"
            "    $ sudo apt remove nginx\n"
            "''')\n"
            "print(apt_output)"
        ),
        (
            "# --- yum/dnf: RHEL/CentOS package management ---\n"
            "import textwrap\n\n"
            "yum_output = textwrap.dedent('''\n"
            "    # Install a package with dnf\n"
            "    $ sudo dnf install httpd\n"
            "    Dependencies resolved.\n"
            "    =====================================\n"
            "     Package    Arch    Version    Repo    Size\n"
            "    =====================================\n"
            "     httpd      x86_64  2.4.57     appstream  1.4 M\n"
            "    Install  1 Package\n"
            "    Is this ok [y/N]: y\n\n"
            "    # List installed packages\n"
            "    $ rpm -qa | grep python\n"
            "    python3-3.9.18-1.el9.x86_64\n"
            "    python3-libs-3.9.18-1.el9.x86_64\n"
            "    python3-pip-21.2.3-7.el9.noarch\n"
            "''')\n"
            "print(yum_output)"
        ),
    ]

    mcqs = [
        MCQ(
            question="Which command updates the local package index on a Debian/Ubuntu system?",
            options={
                "A": "apt upgrade",
                "B": "apt update",
                "C": "apt install --update",
                "D": "dpkg --update",
            },
            correct="B",
            explanation=(
                "`apt update` refreshes the local package index from "
                "configured repositories. This downloads the latest package "
                "lists but does NOT install or upgrade any packages."
            ),
            distractors={
                "A": "`apt upgrade` installs available upgrades for installed packages — it doesn't refresh the index.",
                "C": "There is no `--update` flag for `apt install`.",
                "D": "`dpkg` is the low-level package tool; it doesn't have an `--update` option for repositories.",
            },
            mcq_type="command",
        ),
        MCQ(
            question="On a RHEL 8+ system, which package manager is the recommended replacement for yum?",
            options={
                "A": "apt",
                "B": "rpm",
                "C": "dnf",
                "D": "snap",
            },
            correct="C",
            explanation=(
                "`dnf` (Dandified YUM) is the next-generation package manager "
                "for Fedora and RHEL 8+. It replaces `yum` with better "
                "dependency resolution and performance."
            ),
            distractors={
                "A": "`apt` is for Debian/Ubuntu systems, not RHEL.",
                "B": "`rpm` is the low-level package tool, not a full replacement for yum.",
                "D": "`snap` is a universal package format from Canonical, not the RHEL default.",
            },
            mcq_type="conceptual",
        ),
    ]

    return TopicSection(
        title="Package Management",
        difficulty="Beginner",
        explanation=explanation,
        examples=examples,
        practice=mcqs,
        key_takeaways=[
            "`apt update` refreshes the index; `apt upgrade` installs updates — they're different steps.",
            "Debian/Ubuntu uses `.deb` packages with `apt`; RHEL/CentOS uses `.rpm` with `yum`/`dnf`.",
            "`dnf` is the modern replacement for `yum` on RHEL 8+ and Fedora.",
            "Always run `apt update` before `apt install` to ensure you get the latest version.",
            "Use `dpkg -l` or `rpm -qa` to list all installed packages on the respective distro.",
        ],
    )


# ---------------------------------------------------------------------------
# Mid-Level sections
# ---------------------------------------------------------------------------

def _mid_level_sections() -> list[TopicSection]:
    return [
        _process_scheduling_memory(),
        _shell_scripting(),
        _networking_commands(),
        _systemd_service_management(),
        _log_analysis(),
        _docker_container_basics(),
        _cicd_pipeline_concepts(),
        _kubernetes_basics(),
        _pxe_boot_overview(),
    ]


def _process_scheduling_memory() -> TopicSection:
    explanation = (
        "### Process Scheduling and Memory Management\n\n"
        "**CPU Scheduling** determines which process runs on the CPU and for "
        "how long. The kernel's scheduler makes these decisions.\n\n"
        "**Common scheduling algorithms:**\n"
        "- **First-Come, First-Served (FCFS):** Processes run in arrival order. "
        "Simple but can cause the *convoy effect* (short jobs wait behind long ones).\n"
        "- **Shortest Job First (SJF):** Runs the shortest job next. Optimal "
        "average wait time but requires knowing job lengths in advance.\n"
        "- **Round Robin (RR):** Each process gets a fixed *time quantum* "
        "(e.g., 10ms). After the quantum expires, the process goes to the "
        "back of the queue. Fair and responsive.\n"
        "- **Priority Scheduling:** Each process has a priority. Higher-priority "
        "processes run first. Risk of *starvation* (low-priority processes "
        "never run) — solved by *aging*.\n\n"
        "**Linux uses the Completely Fair Scheduler (CFS)** — a weighted "
        "fair-queuing scheduler that gives each process a fair share of CPU "
        "time based on its nice value.\n\n"
        "**Memory Management:**\n"
        "- **Virtual Memory:** Each process sees its own address space, mapped "
        "to physical memory by the MMU (Memory Management Unit).\n"
        "- **Paging:** Memory is divided into fixed-size *pages* (typically 4KB). "
        "The OS maps virtual pages to physical *frames*.\n"
        "- **Page Fault:** Occurs when a process accesses a page not in physical "
        "memory. The OS loads it from disk (swap).\n"
        "- **Swap:** Disk space used as overflow when physical RAM is full. "
        "Swapping is slow — excessive swapping is called *thrashing*."
    )

    examples = [
        (
            "# --- Round Robin scheduling simulation ---\n"
            "# Demonstrates how RR scheduling works with a time quantum\n\n"
            "from collections import deque\n\n"
            "def round_robin(processes: list[tuple[str, int]], quantum: int) -> list[str]:\n"
            "    \"\"\"\n"
            "    Simulate Round Robin scheduling.\n"
            "    processes: list of (name, burst_time) tuples\n"
            "    quantum: time slice for each process\n"
            "    Returns: execution order log\n"
            "    \"\"\"\n"
            "    queue = deque([(name, burst) for name, burst in processes])\n"
            "    log = []  # execution order\n"
            "    time = 0\n\n"
            "    while queue:\n"
            "        name, remaining = queue.popleft()\n"
            "        # Process runs for min(quantum, remaining) time\n"
            "        run_time = min(quantum, remaining)\n"
            "        time += run_time\n"
            "        remaining -= run_time\n"
            "        log.append(f'{name}(ran {run_time}ms, t={time}ms)')\n\n"
            "        if remaining > 0:\n"
            "            queue.append((name, remaining))  # back to queue\n\n"
            "    return log\n\n"
            "# Example: 3 processes with quantum = 4ms\n"
            "processes = [('P1', 10), ('P2', 4), ('P3', 6)]\n"
            "for entry in round_robin(processes, quantum=4):\n"
            "    print(entry)\n"
            "# P1(ran 4ms, t=4ms)\n"
            "# P2(ran 4ms, t=8ms)    <- P2 finishes\n"
            "# P3(ran 4ms, t=12ms)\n"
            "# P1(ran 4ms, t=16ms)\n"
            "# P3(ran 2ms, t=18ms)   <- P3 finishes\n"
            "# P1(ran 2ms, t=20ms)   <- P1 finishes"
        ),
        (
            "# --- Checking memory and swap usage ---\n"
            "import textwrap\n\n"
            "mem_output = textwrap.dedent('''\n"
            "    $ free -h\n"
            "                  total    used    free   shared  buff/cache  available\n"
            "    Mem:           16Gi    8.2Gi   2.1Gi   512Mi      5.7Gi      7.0Gi\n"
            "    Swap:          4.0Gi   256Mi   3.7Gi\n\n"
            "    $ cat /proc/meminfo | head -5\n"
            "    MemTotal:       16384000 kB\n"
            "    MemFree:         2201600 kB\n"
            "    MemAvailable:    7340032 kB\n"
            "    Buffers:          524288 kB\n"
            "    Cached:          5242880 kB\n\n"
            "    # Check swap usage\n"
            "    $ swapon --show\n"
            "    NAME      TYPE  SIZE  USED PRIO\n"
            "    /dev/sda2 partition 4G 256M   -2\n"
            "''')\n"
            "print(mem_output)"
        ),
    ]

    mcqs = [
        MCQ(
            question=(
                "In Round Robin scheduling with a time quantum of 5ms, "
                "what happens when a process has used its full quantum but "
                "hasn't finished?"
            ),
            options={
                "A": "The process is terminated",
                "B": "The process is moved to the back of the ready queue",
                "C": "The process continues running until completion",
                "D": "The process is moved to swap space",
            },
            correct="B",
            explanation=(
                "In Round Robin, when a process exhausts its time quantum, "
                "it is preempted and placed at the back of the ready queue. "
                "It will get another turn when all other processes have had "
                "their quantum."
            ),
            distractors={
                "A": "RR doesn't terminate processes — it preempts them and re-queues them.",
                "C": "That would be FCFS behavior, not Round Robin. RR enforces time slicing.",
                "D": "Swap is for memory management, not CPU scheduling.",
            },
            mcq_type="conceptual",
        ),
        MCQ(
            question="What is thrashing in the context of virtual memory?",
            options={
                "A": "A process using too much CPU time",
                "B": "Excessive page faults causing the system to spend most time swapping",
                "C": "A disk drive failing due to excessive writes",
                "D": "A network interface dropping packets under load",
            },
            correct="B",
            explanation=(
                "Thrashing occurs when the system spends more time handling "
                "page faults (swapping pages in and out of memory) than "
                "executing actual process instructions. It happens when "
                "physical memory is severely overcommitted."
            ),
            distractors={
                "A": "High CPU usage is not thrashing — thrashing is specifically about memory/swap.",
                "C": "Disk failure is a hardware issue, not related to virtual memory thrashing.",
                "D": "Packet dropping is a network issue, not a memory management concept.",
            },
            mcq_type="conceptual",
        ),
    ]

    return TopicSection(
        title="Process Scheduling and Memory Management",
        difficulty="Mid-Level",
        explanation=explanation,
        examples=examples,
        practice=mcqs,
        key_takeaways=[
            "Round Robin gives each process a fixed time quantum — fair but adds context-switch overhead.",
            "Priority scheduling can cause starvation; aging solves this by gradually increasing priority.",
            "Linux uses CFS (Completely Fair Scheduler) — nice values affect CPU share.",
            "Virtual memory + paging lets each process see its own address space.",
            "Thrashing = excessive swapping. Monitor with `free -h` and `vmstat`.",
        ],
    )


def _shell_scripting() -> TopicSection:
    explanation = (
        "### Shell Scripting Fundamentals\n\n"
        "Shell scripts automate repetitive tasks. Bash is the most common "
        "shell on Linux systems.\n\n"
        "**Variables:**\n"
        "- `NAME=\"value\"` — no spaces around `=`\n"
        "- `$NAME` or `${NAME}` — reference a variable\n"
        "- `$1`, `$2`, ... — positional parameters (script arguments)\n"
        "- `$?` — exit code of last command (0 = success)\n"
        "- `$#` — number of arguments\n\n"
        "**Conditionals:**\n"
        "```bash\n"
        "if [ condition ]; then\n"
        "    # commands\n"
        "elif [ condition ]; then\n"
        "    # commands\n"
        "else\n"
        "    # commands\n"
        "fi\n"
        "```\n\n"
        "**Loops:**\n"
        "```bash\n"
        "for item in list; do\n"
        "    echo $item\n"
        "done\n\n"
        "while [ condition ]; do\n"
        "    # commands\n"
        "done\n"
        "```\n\n"
        "**Functions:**\n"
        "```bash\n"
        "my_function() {\n"
        "    echo \"Arg 1: $1\"\n"
        "    return 0\n"
        "}\n"
        "```\n\n"
        "**Exit codes:** 0 = success, non-zero = failure. Always check `$?` "
        "or use `set -e` to exit on first error."
    )

    examples = [
        (
            "# --- Shell script examples (shown as strings for reference) ---\n"
            "import textwrap\n\n"
            "script_example = textwrap.dedent('''\n"
            "    #!/bin/bash\n"
            "    # health_check.sh — Check if a service is running\n"
            "    set -e  # Exit on error\n\n"
            "    SERVICE=$1\n"
            "    if [ -z \"$SERVICE\" ]; then\n"
            "        echo \"Usage: $0 <service_name>\"\n"
            "        exit 1\n"
            "    fi\n\n"
            "    if systemctl is-active --quiet \"$SERVICE\"; then\n"
            "        echo \"[OK] $SERVICE is running\"\n"
            "        exit 0\n"
            "    else\n"
            "        echo \"[FAIL] $SERVICE is not running\"\n"
            "        exit 1\n"
            "    fi\n"
            "''')\n"
            "print('--- Health Check Script ---')\n"
            "print(script_example)\n\n"
            "loop_example = textwrap.dedent('''\n"
            "    #!/bin/bash\n"
            "    # check_servers.sh — Ping a list of servers\n\n"
            "    SERVERS=(\"192.168.1.1\" \"192.168.1.2\" \"192.168.1.3\")\n\n"
            "    for server in \"${SERVERS[@]}\"; do\n"
            "        if ping -c 1 -W 2 \"$server\" > /dev/null 2>&1; then\n"
            "            echo \"[UP]   $server\"\n"
            "        else\n"
            "            echo \"[DOWN] $server\"\n"
            "        fi\n"
            "    done\n"
            "''')\n"
            "print('--- Server Check Script ---')\n"
            "print(loop_example)"
        ),
        (
            "# --- Functions and exit codes ---\n"
            "import textwrap\n\n"
            "func_example = textwrap.dedent('''\n"
            "    #!/bin/bash\n"
            "    # deploy.sh — Simple deployment script with functions\n\n"
            "    log() {\n"
            "        echo \"[$(date +\\'%Y-%m-%d %H:%M:%S\\')] $1\"\n"
            "    }\n\n"
            "    check_dependencies() {\n"
            "        for cmd in git docker docker-compose; do\n"
            "            if ! command -v \"$cmd\" &> /dev/null; then\n"
            "                log \"ERROR: $cmd is not installed\"\n"
            "                return 1\n"
            "            fi\n"
            "        done\n"
            "        log \"All dependencies found\"\n"
            "        return 0\n"
            "    }\n\n"
            "    # Main\n"
            "    log \"Starting deployment...\"\n"
            "    if check_dependencies; then\n"
            "        log \"Pulling latest code...\"\n"
            "        git pull origin main\n"
            "        log \"Building containers...\"\n"
            "        docker-compose build\n"
            "        log \"Deployment complete!\"\n"
            "    else\n"
            "        log \"Deployment aborted.\"\n"
            "        exit 1\n"
            "    fi\n\n"
            "    $ bash deploy.sh\n"
            "    [2024-01-15 10:30:00] Starting deployment...\n"
            "    [2024-01-15 10:30:00] All dependencies found\n"
            "    [2024-01-15 10:30:01] Pulling latest code...\n"
            "    [2024-01-15 10:30:05] Building containers...\n"
            "    [2024-01-15 10:30:30] Deployment complete!\n"
            "''')\n"
            "print(func_example)"
        ),
    ]

    mcqs = [
        MCQ(
            question=(
                "In a Bash script, what does `$?` represent?"
            ),
            options={
                "A": "The process ID of the current script",
                "B": "The number of arguments passed to the script",
                "C": "The exit code of the last executed command",
                "D": "The name of the current script",
            },
            correct="C",
            explanation=(
                "`$?` holds the exit status of the most recently executed "
                "command. A value of 0 means success; any non-zero value "
                "indicates an error."
            ),
            distractors={
                "A": "The current script's PID is `$$`, not `$?`.",
                "B": "The number of arguments is `$#`, not `$?`.",
                "D": "The script name is `$0`, not `$?`.",
            },
            mcq_type="code_output",
        ),
        MCQ(
            question=(
                "What is the output of this Bash snippet?\n\n"
                "```bash\n"
                "count=0\n"
                "for i in 1 2 3 4 5; do\n"
                "    count=$((count + i))\n"
                "done\n"
                "echo $count\n"
                "```"
            ),
            options={
                "A": "5",
                "B": "10",
                "C": "15",
                "D": "0",
            },
            correct="C",
            explanation=(
                "The loop adds 1+2+3+4+5 = 15. `$((count + i))` performs "
                "arithmetic expansion in Bash."
            ),
            distractors={
                "A": "5 would be the result if only the last value was assigned, not accumulated.",
                "B": "10 would be the sum of 1+2+3+4, missing the last iteration.",
                "D": "0 is the initial value; the loop modifies count on each iteration.",
            },
            mcq_type="code_output",
        ),
    ]

    return TopicSection(
        title="Shell Scripting Fundamentals",
        difficulty="Mid-Level",
        explanation=explanation,
        examples=examples,
        practice=mcqs,
        key_takeaways=[
            "`$?` = last exit code, `$$` = current PID, `$#` = argument count, `$0` = script name.",
            "Use `set -e` to make scripts exit on the first error.",
            "Always quote variables: `\"$VAR\"` prevents word splitting and globbing issues.",
            "Functions return exit codes (0-255); use `$?` to check or chain with `&&`/`||`.",
            "Use `[[ ]]` (double brackets) for safer conditionals in Bash — supports regex and pattern matching.",
        ],
    )


def _networking_commands() -> TopicSection:
    explanation = (
        "### Networking Commands\n\n"
        "Linux provides a rich set of networking tools for diagnostics, "
        "monitoring, and troubleshooting.\n\n"
        "**Connection and socket info:**\n"
        "- `ss` — modern replacement for `netstat`; shows socket statistics\n"
        "- `netstat` — legacy tool for network connections (still widely used)\n\n"
        "**Interface and routing:**\n"
        "- `ip addr` — show/manage IP addresses (replaces `ifconfig`)\n"
        "- `ip route` — show/manage routing table\n\n"
        "**Connectivity testing:**\n"
        "- `ping` — test reachability (ICMP echo)\n"
        "- `traceroute` — show the path packets take to a destination\n"
        "- `curl` — transfer data from/to a server (HTTP, FTP, etc.)\n\n"
        "**DNS resolution:**\n"
        "- `dig` — DNS lookup utility (detailed output)\n"
        "- `nslookup` — simpler DNS query tool"
    )

    examples = [
        (
            "# --- ss and netstat: viewing connections ---\n"
            "import textwrap\n\n"
            "ss_output = textwrap.dedent('''\n"
            "    # Show listening TCP ports\n"
            "    $ ss -tlnp\n"
            "    State   Recv-Q  Send-Q  Local Address:Port  Peer Address:Port  Process\n"
            "    LISTEN  0       128     0.0.0.0:22          0.0.0.0:*          users:((\"sshd\",pid=1234))\n"
            "    LISTEN  0       511     0.0.0.0:80          0.0.0.0:*          users:((\"nginx\",pid=5678))\n"
            "    LISTEN  0       128     0.0.0.0:443         0.0.0.0:*          users:((\"nginx\",pid=5678))\n"
            "    LISTEN  0       128     127.0.0.1:5432      0.0.0.0:*          users:((\"postgres\",pid=9012))\n\n"
            "    # Show all established connections\n"
            "    $ ss -tnp state established\n"
            "    Recv-Q  Send-Q  Local Address:Port  Peer Address:Port  Process\n"
            "    0       0       10.0.1.5:22         10.0.1.100:54321   users:((\"sshd\",pid=2345))\n"
            "    0       0       10.0.1.5:80         10.0.1.200:43210   users:((\"nginx\",pid=5678))\n\n"
            "    # Legacy: netstat equivalent\n"
            "    $ netstat -tlnp\n"
            "    Proto Recv-Q Send-Q Local Address    Foreign Address  State   PID/Program\n"
            "    tcp   0      0      0.0.0.0:22       0.0.0.0:*        LISTEN  1234/sshd\n"
            "    tcp   0      0      0.0.0.0:80       0.0.0.0:*        LISTEN  5678/nginx\n"
            "''')\n"
            "print(ss_output)"
        ),
        (
            "# --- ping, traceroute, curl, dig ---\n"
            "import textwrap\n\n"
            "net_output = textwrap.dedent('''\n"
            "    # Ping a host (3 packets)\n"
            "    $ ping -c 3 8.8.8.8\n"
            "    PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.\n"
            "    64 bytes from 8.8.8.8: icmp_seq=1 ttl=118 time=12.3 ms\n"
            "    64 bytes from 8.8.8.8: icmp_seq=2 ttl=118 time=11.8 ms\n"
            "    64 bytes from 8.8.8.8: icmp_seq=3 ttl=118 time=12.1 ms\n"
            "    --- 8.8.8.8 ping statistics ---\n"
            "    3 packets transmitted, 3 received, 0% packet loss, time 2003ms\n\n"
            "    # Trace route to a host\n"
            "    $ traceroute 8.8.8.8\n"
            "    traceroute to 8.8.8.8 (8.8.8.8), 30 hops max\n"
            "     1  gateway (192.168.1.1)  1.234 ms\n"
            "     2  isp-router (10.0.0.1)  5.678 ms\n"
            "     3  8.8.8.8 (8.8.8.8)  12.345 ms\n\n"
            "    # HTTP request with curl\n"
            "    $ curl -s -o /dev/null -w \"%{http_code}\" https://example.com\n"
            "    200\n\n"
            "    # DNS lookup with dig\n"
            "    $ dig example.com +short\n"
            "    93.184.216.34\n\n"
            "    # DNS lookup with nslookup\n"
            "    $ nslookup example.com\n"
            "    Server:    127.0.0.53\n"
            "    Address:   127.0.0.53#53\n"
            "    Non-authoritative answer:\n"
            "    Name: example.com\n"
            "    Address: 93.184.216.34\n"
            "''')\n"
            "print(net_output)"
        ),
    ]

    mcqs = [
        MCQ(
            question="Which command shows all listening TCP ports along with the process using each port?",
            options={
                "A": "ss -tlnp",
                "B": "ping -l",
                "C": "ip addr show",
                "D": "traceroute -t",
            },
            correct="A",
            explanation=(
                "`ss -tlnp` shows TCP (-t) listening (-l) sockets in numeric "
                "format (-n) with process info (-p). This is the modern "
                "replacement for `netstat -tlnp`."
            ),
            distractors={
                "B": "`ping` tests connectivity; it doesn't show listening ports.",
                "C": "`ip addr show` displays IP addresses, not listening ports.",
                "D": "`traceroute` shows the network path to a host, not local ports.",
            },
            mcq_type="command",
        ),
        MCQ(
            question=(
                "What does the following curl command output?\n\n"
                "```bash\n"
                "curl -s -o /dev/null -w \"%{http_code}\" https://example.com\n"
                "```"
            ),
            options={
                "A": "The full HTML content of the page",
                "B": "The HTTP status code only (e.g., 200)",
                "C": "The response headers",
                "D": "The DNS resolution time",
            },
            correct="B",
            explanation=(
                "`-s` = silent mode, `-o /dev/null` = discard the body, "
                "`-w \"%{http_code}\"` = print only the HTTP status code. "
                "This is a common pattern for health checks."
            ),
            distractors={
                "A": "The body is discarded to /dev/null; only the status code is printed.",
                "C": "Headers would require `-I` or `-D`; `-w` with `%{http_code}` prints the status code.",
                "D": "DNS time would use `%{time_namelookup}`, not `%{http_code}`.",
            },
            mcq_type="code_output",
        ),
    ]

    return TopicSection(
        title="Networking Commands",
        difficulty="Mid-Level",
        explanation=explanation,
        examples=examples,
        practice=mcqs,
        key_takeaways=[
            "`ss` is the modern replacement for `netstat` — use `ss -tlnp` for listening ports.",
            "`ip addr` replaces `ifconfig`; `ip route` replaces `route`.",
            "`curl -s -o /dev/null -w '%{http_code}'` is a quick HTTP health check pattern.",
            "`dig +short` gives a clean DNS answer; `nslookup` is simpler but less detailed.",
            "`traceroute` helps identify where network issues occur along the path.",
        ],
    )


def _systemd_service_management() -> TopicSection:
    explanation = (
        "### Systemd Service Management\n\n"
        "**systemd** is the init system and service manager for most modern "
        "Linux distributions. It manages services (daemons), mount points, "
        "timers, and more.\n\n"
        "**Key `systemctl` commands:**\n"
        "- `systemctl start <service>` — start a service\n"
        "- `systemctl stop <service>` — stop a service\n"
        "- `systemctl restart <service>` — restart a service\n"
        "- `systemctl enable <service>` — start on boot\n"
        "- `systemctl disable <service>` — don't start on boot\n"
        "- `systemctl status <service>` — show service status\n"
        "- `systemctl list-units --type=service` — list all services\n\n"
        "**Service unit files** live in `/etc/systemd/system/` (custom) or "
        "`/lib/systemd/system/` (package-installed).\n\n"
        "**journalctl** reads logs from the systemd journal:\n"
        "- `journalctl -u <service>` — logs for a specific service\n"
        "- `journalctl -f` — follow (tail) the journal\n"
        "- `journalctl --since '1 hour ago'` — time-based filtering"
    )

    examples = [
        (
            "# --- systemctl: managing services ---\n"
            "import textwrap\n\n"
            "systemctl_output = textwrap.dedent('''\n"
            "    # Check status of nginx\n"
            "    $ systemctl status nginx\n"
            "    ● nginx.service - A high performance web server\n"
            "       Loaded: loaded (/lib/systemd/system/nginx.service; enabled)\n"
            "       Active: active (running) since Mon 2024-01-15 10:00:00 UTC; 2h ago\n"
            "     Main PID: 1234 (nginx)\n"
            "        Tasks: 3 (limit: 4915)\n"
            "       Memory: 12.5M\n"
            "       CGroup: /system.slice/nginx.service\n"
            "               ├─1234 nginx: master process /usr/sbin/nginx\n"
            "               └─1235 nginx: worker process\n\n"
            "    # Start, stop, restart\n"
            "    $ sudo systemctl start nginx\n"
            "    $ sudo systemctl stop nginx\n"
            "    $ sudo systemctl restart nginx\n\n"
            "    # Enable on boot\n"
            "    $ sudo systemctl enable nginx\n"
            "    Created symlink /etc/systemd/system/multi-user.target.wants/nginx.service\n"
            "''')\n"
            "print(systemctl_output)"
        ),
        (
            "# --- Creating a custom service unit file ---\n"
            "import textwrap\n\n"
            "unit_file = textwrap.dedent('''\n"
            "    # /etc/systemd/system/myapp.service\n"
            "    [Unit]\n"
            "    Description=My Python Application\n"
            "    After=network.target\n\n"
            "    [Service]\n"
            "    Type=simple\n"
            "    User=appuser\n"
            "    WorkingDirectory=/opt/myapp\n"
            "    ExecStart=/usr/bin/python3 /opt/myapp/main.py\n"
            "    Restart=on-failure\n"
            "    RestartSec=5\n"
            "    Environment=ENV=production\n\n"
            "    [Install]\n"
            "    WantedBy=multi-user.target\n\n"
            "    # After creating the file:\n"
            "    $ sudo systemctl daemon-reload    # reload unit files\n"
            "    $ sudo systemctl start myapp      # start the service\n"
            "    $ sudo systemctl enable myapp     # enable on boot\n"
            "    $ journalctl -u myapp -f          # follow logs\n"
            "''')\n"
            "print(unit_file)"
        ),
    ]

    mcqs = [
        MCQ(
            question="What does `systemctl enable nginx` do?",
            options={
                "A": "Starts the nginx service immediately",
                "B": "Configures nginx to start automatically on boot",
                "C": "Reloads the nginx configuration",
                "D": "Shows the current status of nginx",
            },
            correct="B",
            explanation=(
                "`systemctl enable` creates a symlink so the service starts "
                "automatically at boot. It does NOT start the service "
                "immediately — use `systemctl start` for that."
            ),
            distractors={
                "A": "`enable` only sets up auto-start on boot. Use `start` to start immediately.",
                "C": "To reload config, use `systemctl reload nginx` or `nginx -s reload`.",
                "D": "To show status, use `systemctl status nginx`.",
            },
            mcq_type="command",
        ),
        MCQ(
            question=(
                "Which section of a systemd unit file specifies the command "
                "to run when starting the service?"
            ),
            options={
                "A": "[Unit] — Description",
                "B": "[Service] — ExecStart",
                "C": "[Install] — WantedBy",
                "D": "[Service] — Restart",
            },
            correct="B",
            explanation=(
                "The `ExecStart` directive in the `[Service]` section "
                "specifies the command and arguments to execute when the "
                "service is started."
            ),
            distractors={
                "A": "[Unit] Description is a human-readable description, not the start command.",
                "C": "[Install] WantedBy specifies which target pulls in this service on boot.",
                "D": "[Service] Restart defines the restart policy (on-failure, always, etc.).",
            },
            mcq_type="conceptual",
        ),
    ]

    return TopicSection(
        title="Systemd Service Management",
        difficulty="Mid-Level",
        explanation=explanation,
        examples=examples,
        practice=mcqs,
        key_takeaways=[
            "`systemctl enable` ≠ `systemctl start` — enable sets up boot start, start runs now.",
            "Custom service files go in `/etc/systemd/system/`; run `daemon-reload` after changes.",
            "A unit file has three sections: [Unit] (metadata), [Service] (how to run), [Install] (boot target).",
            "`journalctl -u <service> -f` is the go-to for tailing service logs.",
            "`Restart=on-failure` with `RestartSec=5` gives automatic recovery with a delay.",
        ],
    )


def _log_analysis() -> TopicSection:
    explanation = (
        "### Log Analysis\n\n"
        "Effective log analysis is critical for debugging, monitoring, and "
        "incident response. Linux stores logs in standard locations and "
        "provides powerful tools to query them.\n\n"
        "**Common log locations:**\n"
        "- `/var/log/syslog` — general system log (Debian/Ubuntu)\n"
        "- `/var/log/messages` — general system log (RHEL/CentOS)\n"
        "- `/var/log/auth.log` — authentication events\n"
        "- `/var/log/kern.log` — kernel messages\n"
        "- `/var/log/nginx/` — web server logs\n"
        "- `/var/log/apt/` — package manager logs\n\n"
        "**Key tools:**\n"
        "- `journalctl` — query the systemd journal\n"
        "- `dmesg` — kernel ring buffer messages\n"
        "- `grep` / `awk` — text processing for log analysis\n"
        "- `tail -f` — follow a log file in real time\n"
        "- `less` / `more` — paginate through large log files"
    )

    examples = [
        (
            "# --- journalctl: querying the systemd journal ---\n"
            "import textwrap\n\n"
            "journal_output = textwrap.dedent('''\n"
            "    # View logs for a specific service\n"
            "    $ journalctl -u nginx --since \"1 hour ago\"\n"
            "    Jan 15 10:00:00 server nginx[1234]: Starting nginx...\n"
            "    Jan 15 10:00:01 server nginx[1234]: nginx started successfully\n"
            "    Jan 15 10:30:15 server nginx[1234]: 10.0.1.100 GET /api/health 200\n"
            "    Jan 15 10:45:22 server nginx[1234]: 10.0.1.200 GET /api/data 500\n\n"
            "    # View kernel messages\n"
            "    $ dmesg | tail -5\n"
            "    [12345.678] usb 2-1: new high-speed USB device number 3\n"
            "    [12345.789] usb 2-1: New USB device found, idVendor=0781\n"
            "    [12346.012] sd 2:0:0:0: [sdb] 30031872 512-byte sectors\n"
            "    [12346.123] sd 2:0:0:0: [sdb] Write Protect is off\n"
            "    [12346.234] sdb: sdb1\n\n"
            "    # Show only errors from the journal\n"
            "    $ journalctl -p err --since today\n"
            "    Jan 15 10:45:22 server nginx[1234]: upstream timed out\n"
            "    Jan 15 11:00:01 server postgres[5678]: FATAL: connection limit exceeded\n"
            "''')\n"
            "print(journal_output)"
        ),
        (
            "# --- grep and awk for log analysis ---\n"
            "import textwrap\n\n"
            "analysis_output = textwrap.dedent('''\n"
            "    # Count HTTP 500 errors in nginx access log\n"
            "    $ grep \" 500 \" /var/log/nginx/access.log | wc -l\n"
            "    42\n\n"
            "    # Extract unique IP addresses from access log\n"
            "    $ awk \\'{print $1}\\' /var/log/nginx/access.log | sort -u | head -5\n"
            "    10.0.1.100\n"
            "    10.0.1.101\n"
            "    10.0.1.200\n"
            "    192.168.1.50\n"
            "    192.168.1.51\n\n"
            "    # Find top 10 IPs by request count\n"
            "    $ awk \\'{print $1}\\' /var/log/nginx/access.log | sort | uniq -c | sort -rn | head -10\n"
            "        1523 10.0.1.100\n"
            "         987 10.0.1.200\n"
            "         456 192.168.1.50\n"
            "         234 10.0.1.101\n\n"
            "    # Monitor auth failures in real time\n"
            "    $ tail -f /var/log/auth.log | grep \"Failed password\"\n"
            "    Jan 15 11:23:45 server sshd[9876]: Failed password for root from 10.0.1.99\n"
            "''')\n"
            "print(analysis_output)"
        ),
    ]

    mcqs = [
        MCQ(
            question="Which command shows only error-level messages from the systemd journal since today?",
            options={
                "A": "journalctl -u errors --since today",
                "B": "journalctl -p err --since today",
                "C": "dmesg --level=error --today",
                "D": "grep ERROR /var/log/syslog",
            },
            correct="B",
            explanation=(
                "`journalctl -p err` filters by priority level 'err' (error). "
                "`--since today` limits to entries from today. This shows all "
                "error-level journal entries across all services."
            ),
            distractors={
                "A": "`-u` specifies a service unit name, not a priority level.",
                "C": "`dmesg` shows kernel messages only and doesn't have `--today` syntax.",
                "D": "`grep ERROR` does a text search — it doesn't filter by syslog priority level.",
            },
            mcq_type="command",
        ),
        MCQ(
            question=(
                "What does the following command pipeline do?\n\n"
                "```bash\n"
                "awk '{print $1}' access.log | sort | uniq -c | sort -rn | head -5\n"
                "```"
            ),
            options={
                "A": "Shows the 5 most recent log entries",
                "B": "Shows the 5 IP addresses with the most requests",
                "C": "Shows the 5 largest log files",
                "D": "Shows the 5 most common HTTP status codes",
            },
            correct="B",
            explanation=(
                "`awk '{print $1}'` extracts the first field (IP address in "
                "standard access logs). `sort | uniq -c` counts occurrences. "
                "`sort -rn` sorts numerically in reverse (highest first). "
                "`head -5` shows the top 5."
            ),
            distractors={
                "A": "This pipeline counts and ranks, not shows recent entries. Use `tail -5` for recent.",
                "C": "This operates on log content, not file sizes.",
                "D": "The first field ($1) in access logs is typically the IP address, not the status code.",
            },
            mcq_type="code_output",
        ),
    ]

    return TopicSection(
        title="Log Analysis",
        difficulty="Mid-Level",
        explanation=explanation,
        examples=examples,
        practice=mcqs,
        key_takeaways=[
            "`journalctl -u <service>` is the primary tool for viewing service logs on systemd systems.",
            "`journalctl -p err` filters by priority — useful for finding errors quickly.",
            "`dmesg` shows kernel messages — useful for hardware and driver issues.",
            "`awk '{print $1}' | sort | uniq -c | sort -rn` is the classic \"top N\" log analysis pattern.",
            "Know your log locations: `/var/log/syslog` (Debian), `/var/log/messages` (RHEL).",
        ],
    )


def _docker_container_basics() -> TopicSection:
    explanation = (
        "### Docker Container Basics (NVIDIA-Relevant)\n\n"
        "Docker packages applications and their dependencies into lightweight, "
        "portable **containers**. Containers share the host OS kernel but run "
        "in isolated user spaces.\n\n"
        "**Key concepts:**\n"
        "- **Image:** A read-only template with the application and its "
        "dependencies. Built from a `Dockerfile`.\n"
        "- **Container:** A running instance of an image.\n"
        "- **Registry:** A repository for images (e.g., Docker Hub, NVIDIA NGC).\n"
        "- **Volume:** Persistent storage that survives container restarts.\n\n"
        "**Essential commands:**\n"
        "- `docker run` — create and start a container\n"
        "- `docker ps` — list running containers\n"
        "- `docker images` — list local images\n"
        "- `docker build` — build an image from a Dockerfile\n"
        "- `docker stop` / `docker rm` — stop and remove containers\n"
        "- `docker-compose up` — start multi-container applications\n\n"
        "**NVIDIA context:** NVIDIA uses Docker extensively for GPU-accelerated "
        "workloads (nvidia-docker / NVIDIA Container Toolkit), CI/CD pipelines, "
        "and reproducible test environments."
    )

    examples = [
        (
            "# --- Docker commands ---\n"
            "import textwrap\n\n"
            "docker_output = textwrap.dedent('''\n"
            "    # Run a container (detached, with port mapping)\n"
            "    $ docker run -d -p 8080:80 --name web nginx\n"
            "    a1b2c3d4e5f6...\n\n"
            "    # List running containers\n"
            "    $ docker ps\n"
            "    CONTAINER ID  IMAGE  COMMAND                 STATUS        PORTS                  NAMES\n"
            "    a1b2c3d4e5f6  nginx  \"/docker-entrypoint…\"  Up 2 minutes  0.0.0.0:8080->80/tcp   web\n\n"
            "    # List local images\n"
            "    $ docker images\n"
            "    REPOSITORY  TAG     IMAGE ID      CREATED       SIZE\n"
            "    nginx       latest  abc123def456  2 weeks ago   187MB\n"
            "    python      3.11    def456abc789  3 weeks ago   1.01GB\n\n"
            "    # View container logs\n"
            "    $ docker logs web\n"
            "    172.17.0.1 - - [15/Jan/2024:10:30:00] \"GET / HTTP/1.1\" 200 615\n\n"
            "    # Stop and remove\n"
            "    $ docker stop web\n"
            "    $ docker rm web\n"
            "''')\n"
            "print(docker_output)"
        ),
        (
            "# --- Dockerfile and docker-compose ---\n"
            "import textwrap\n\n"
            "dockerfile_example = textwrap.dedent('''\n"
            "    # --- Example Dockerfile ---\n"
            "    FROM python:3.11-slim\n"
            "    WORKDIR /app\n"
            "    COPY requirements.txt .\n"
            "    RUN pip install --no-cache-dir -r requirements.txt\n"
            "    COPY . .\n"
            "    EXPOSE 8000\n"
            "    CMD [\"python\", \"app.py\"]\n\n"
            "    # Build the image\n"
            "    $ docker build -t myapp:1.0 .\n"
            "    Step 1/6 : FROM python:3.11-slim\n"
            "    Step 2/6 : WORKDIR /app\n"
            "    ...\n"
            "    Successfully built abc123\n"
            "    Successfully tagged myapp:1.0\n\n"
            "    # --- Example docker-compose.yml ---\n"
            "    version: \"3.8\"\n"
            "    services:\n"
            "      web:\n"
            "        build: .\n"
            "        ports:\n"
            "          - \"8000:8000\"\n"
            "        environment:\n"
            "          - DATABASE_URL=postgres://db:5432/mydb\n"
            "        depends_on:\n"
            "          - db\n"
            "      db:\n"
            "        image: postgres:15\n"
            "        volumes:\n"
            "          - pgdata:/var/lib/postgresql/data\n"
            "    volumes:\n"
            "      pgdata:\n\n"
            "    $ docker-compose up -d\n"
            "    Creating network \"myapp_default\"\n"
            "    Creating myapp_db_1  ... done\n"
            "    Creating myapp_web_1 ... done\n"
            "''')\n"
            "print(dockerfile_example)"
        ),
    ]

    mcqs = [
        MCQ(
            question="What is the difference between a Docker image and a Docker container?",
            options={
                "A": "An image is a running process; a container is a file on disk",
                "B": "An image is a read-only template; a container is a running instance of an image",
                "C": "An image and a container are the same thing",
                "D": "A container is a read-only template; an image is a running instance",
            },
            correct="B",
            explanation=(
                "A Docker image is a read-only template containing the "
                "application code, runtime, libraries, and dependencies. "
                "A container is a running (or stopped) instance created from "
                "an image, with its own writable layer."
            ),
            distractors={
                "A": "This is reversed — the image is the template on disk, the container is the running process.",
                "C": "They are distinct concepts — images are templates, containers are instances.",
                "D": "This is reversed — images are read-only templates, containers are instances.",
            },
            mcq_type="conceptual",
        ),
        MCQ(
            question=(
                "Which command runs an nginx container in detached mode, "
                "mapping host port 8080 to container port 80?"
            ),
            options={
                "A": "docker run -d -p 80:8080 nginx",
                "B": "docker run -d -p 8080:80 nginx",
                "C": "docker start -p 8080:80 nginx",
                "D": "docker run --port 8080:80 nginx",
            },
            correct="B",
            explanation=(
                "`docker run -d` runs in detached mode. `-p 8080:80` maps "
                "host port 8080 to container port 80 (format: host:container). "
                "The image name `nginx` comes last."
            ),
            distractors={
                "A": "`-p 80:8080` maps host port 80 to container port 8080 — the order is reversed.",
                "C": "`docker start` resumes a stopped container; `docker run` creates a new one.",
                "D": "The flag is `-p`, not `--port`.",
            },
            mcq_type="command",
        ),
    ]

    return TopicSection(
        title="Docker Container Basics",
        difficulty="Mid-Level",
        explanation=explanation,
        examples=examples,
        practice=mcqs,
        key_takeaways=[
            "Image = read-only template; Container = running instance of an image.",
            "`docker run -d -p host:container image` is the basic run pattern.",
            "Dockerfile: FROM → WORKDIR → COPY → RUN → EXPOSE → CMD.",
            "docker-compose manages multi-container apps with a single YAML file.",
            "NVIDIA uses Docker + NVIDIA Container Toolkit for GPU workloads.",
        ],
    )


def _cicd_pipeline_concepts() -> TopicSection:
    explanation = (
        "### CI/CD Pipeline Concepts — Jenkins (NVIDIA-Relevant)\n\n"
        "**Continuous Integration (CI)** automatically builds and tests code "
        "on every commit. **Continuous Delivery/Deployment (CD)** automates "
        "releasing tested code to staging or production.\n\n"
        "**Pipeline stages (typical flow):**\n"
        "1. **Source** — code checkout from Git\n"
        "2. **Build** — compile code, build Docker images\n"
        "3. **Test** — run unit tests, integration tests, linting\n"
        "4. **Deploy** — push to staging/production\n\n"
        "**Jenkins** is a widely-used open-source CI/CD server:\n"
        "- **Jenkinsfile** — defines the pipeline as code (Groovy DSL)\n"
        "- **Declarative Pipeline** — structured syntax with `pipeline { }` block\n"
        "- **Stages** — logical groupings of steps\n"
        "- **Steps** — individual commands within a stage\n"
        "- **Agents** — where the pipeline runs (any, docker, specific node)\n\n"
        "**NVIDIA context:** NVIDIA uses Jenkins (and similar tools) for "
        "building drivers, running GPU test suites, and deploying firmware "
        "updates across server fleets."
    )

    examples = [
        (
            "# --- Jenkinsfile example (declarative pipeline) ---\n"
            "import textwrap\n\n"
            "jenkinsfile = textwrap.dedent('''\n"
            "    // Jenkinsfile — Declarative Pipeline\n"
            "    pipeline {\n"
            "        agent any\n\n"
            "        environment {\n"
            "            DOCKER_IMAGE = \"myapp:${BUILD_NUMBER}\"\n"
            "        }\n\n"
            "        stages {\n"
            "            stage(\"Checkout\") {\n"
            "                steps {\n"
            "                    git branch: \"main\", url: \"https://github.com/org/repo.git\"\n"
            "                }\n"
            "            }\n"
            "            stage(\"Build\") {\n"
            "                steps {\n"
            "                    sh \"docker build -t ${DOCKER_IMAGE} .\"\n"
            "                }\n"
            "            }\n"
            "            stage(\"Test\") {\n"
            "                steps {\n"
            "                    sh \"docker run --rm ${DOCKER_IMAGE} pytest tests/\"\n"
            "                }\n"
            "            }\n"
            "            stage(\"Deploy\") {\n"
            "                when {\n"
            "                    branch \"main\"\n"
            "                }\n"
            "                steps {\n"
            "                    sh \"docker push ${DOCKER_IMAGE}\"\n"
            "                    sh \"kubectl set image deployment/myapp myapp=${DOCKER_IMAGE}\"\n"
            "                }\n"
            "            }\n"
            "        }\n"
            "        post {\n"
            "            failure {\n"
            "                echo \"Pipeline failed! Sending notification...\"\n"
            "            }\n"
            "        }\n"
            "    }\n"
            "''')\n"
            "print(jenkinsfile)"
        ),
    ]

    mcqs = [
        MCQ(
            question="In a Jenkins declarative pipeline, which block defines where the pipeline runs?",
            options={
                "A": "stages { }",
                "B": "agent { }",
                "C": "environment { }",
                "D": "post { }",
            },
            correct="B",
            explanation=(
                "The `agent` block specifies where the pipeline or a stage "
                "runs — e.g., `agent any` (any available node), "
                "`agent { docker { image 'python:3.11' } }` (inside a Docker "
                "container), or `agent { label 'gpu-node' }` (specific node)."
            ),
            distractors={
                "A": "`stages` defines the sequence of pipeline stages, not where they run.",
                "C": "`environment` defines environment variables, not execution location.",
                "D": "`post` defines actions to run after stages complete (success, failure, always).",
            },
            mcq_type="conceptual",
        ),
    ]

    return TopicSection(
        title="CI/CD Pipeline Concepts (Jenkins)",
        difficulty="Mid-Level",
        explanation=explanation,
        examples=examples,
        practice=mcqs,
        key_takeaways=[
            "CI/CD automates build → test → deploy on every code change.",
            "Jenkinsfile defines pipeline-as-code using Groovy declarative syntax.",
            "Key blocks: `agent` (where), `stages` (what), `post` (after), `environment` (variables).",
            "The `when` directive controls conditional stage execution (e.g., only on main branch).",
            "NVIDIA uses CI/CD for driver builds, GPU test suites, and firmware deployment.",
        ],
    )


def _kubernetes_basics() -> TopicSection:
    explanation = (
        "### Basic Kubernetes Concepts (NVIDIA-Relevant)\n\n"
        "**Kubernetes (K8s)** is a container orchestration platform that "
        "automates deploying, scaling, and managing containerized applications.\n\n"
        "**Core objects:**\n"
        "- **Pod:** The smallest deployable unit — one or more containers "
        "sharing network and storage.\n"
        "- **Deployment:** Manages a set of identical pods, handles rolling "
        "updates and rollbacks.\n"
        "- **Service:** Exposes pods to the network with a stable IP/DNS name. "
        "Types: ClusterIP (internal), NodePort (external via node port), "
        "LoadBalancer (cloud LB).\n"
        "- **Namespace:** Logical isolation within a cluster.\n\n"
        "**Key `kubectl` commands:**\n"
        "- `kubectl get pods` — list pods\n"
        "- `kubectl get deployments` — list deployments\n"
        "- `kubectl get services` — list services\n"
        "- `kubectl describe pod <name>` — detailed pod info\n"
        "- `kubectl logs <pod>` — view pod logs\n"
        "- `kubectl apply -f <file.yaml>` — apply a configuration\n"
        "- `kubectl delete pod <name>` — delete a pod\n\n"
        "**NVIDIA context:** NVIDIA uses Kubernetes for managing GPU clusters, "
        "scheduling GPU workloads with the NVIDIA device plugin, and running "
        "distributed training jobs."
    )

    examples = [
        (
            "# --- kubectl commands ---\n"
            "import textwrap\n\n"
            "k8s_output = textwrap.dedent('''\n"
            "    # List all pods in the default namespace\n"
            "    $ kubectl get pods\n"
            "    NAME                     READY   STATUS    RESTARTS   AGE\n"
            "    web-app-6d8f9b7c4-abc12  1/1     Running   0          2h\n"
            "    web-app-6d8f9b7c4-def34  1/1     Running   0          2h\n"
            "    redis-5f7b8c9d1-ghi56    1/1     Running   0          5h\n\n"
            "    # List deployments\n"
            "    $ kubectl get deployments\n"
            "    NAME      READY   UP-TO-DATE   AVAILABLE   AGE\n"
            "    web-app   2/2     2            2           2h\n"
            "    redis     1/1     1            1           5h\n\n"
            "    # List services\n"
            "    $ kubectl get services\n"
            "    NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE\n"
            "    kubernetes   ClusterIP   10.96.0.1      <none>        443/TCP        10d\n"
            "    web-app      NodePort    10.96.100.50   <none>        80:30080/TCP   2h\n"
            "    redis        ClusterIP   10.96.100.51   <none>        6379/TCP       5h\n\n"
            "    # View logs from a pod\n"
            "    $ kubectl logs web-app-6d8f9b7c4-abc12\n"
            "    [2024-01-15 10:00:00] Server started on port 80\n"
            "    [2024-01-15 10:30:15] GET /api/health 200 OK\n\n"
            "    # Describe a pod (detailed info)\n"
            "    $ kubectl describe pod web-app-6d8f9b7c4-abc12 | head -10\n"
            "    Name:         web-app-6d8f9b7c4-abc12\n"
            "    Namespace:    default\n"
            "    Node:         worker-1/10.0.1.10\n"
            "    Status:       Running\n"
            "    IP:           10.244.1.5\n"
            "''')\n"
            "print(k8s_output)"
        ),
        (
            "# --- Kubernetes YAML manifests ---\n"
            "import textwrap\n\n"
            "k8s_yaml = textwrap.dedent('''\n"
            "    # --- deployment.yaml ---\n"
            "    apiVersion: apps/v1\n"
            "    kind: Deployment\n"
            "    metadata:\n"
            "      name: web-app\n"
            "    spec:\n"
            "      replicas: 3\n"
            "      selector:\n"
            "        matchLabels:\n"
            "          app: web-app\n"
            "      template:\n"
            "        metadata:\n"
            "          labels:\n"
            "            app: web-app\n"
            "        spec:\n"
            "          containers:\n"
            "          - name: web\n"
            "            image: myapp:1.0\n"
            "            ports:\n"
            "            - containerPort: 80\n\n"
            "    # --- service.yaml ---\n"
            "    apiVersion: v1\n"
            "    kind: Service\n"
            "    metadata:\n"
            "      name: web-app\n"
            "    spec:\n"
            "      type: NodePort\n"
            "      selector:\n"
            "        app: web-app\n"
            "      ports:\n"
            "      - port: 80\n"
            "        targetPort: 80\n"
            "        nodePort: 30080\n\n"
            "    # Apply both\n"
            "    $ kubectl apply -f deployment.yaml\n"
            "    deployment.apps/web-app created\n"
            "    $ kubectl apply -f service.yaml\n"
            "    service/web-app created\n"
            "''')\n"
            "print(k8s_yaml)"
        ),
    ]

    mcqs = [
        MCQ(
            question="What is the smallest deployable unit in Kubernetes?",
            options={
                "A": "Container",
                "B": "Pod",
                "C": "Deployment",
                "D": "Service",
            },
            correct="B",
            explanation=(
                "A Pod is the smallest deployable unit in Kubernetes. It can "
                "contain one or more containers that share the same network "
                "namespace and storage volumes. You don't deploy containers "
                "directly — you deploy pods."
            ),
            distractors={
                "A": "Containers run inside pods. Kubernetes manages pods, not individual containers.",
                "C": "A Deployment manages a set of pods — it's a higher-level abstraction.",
                "D": "A Service provides network access to pods — it's not a deployable unit.",
            },
            mcq_type="conceptual",
        ),
        MCQ(
            question=(
                "Which Kubernetes Service type exposes a service on each "
                "node's IP at a static port?"
            ),
            options={
                "A": "ClusterIP",
                "B": "NodePort",
                "C": "LoadBalancer",
                "D": "ExternalName",
            },
            correct="B",
            explanation=(
                "NodePort exposes the service on each node's IP at a static "
                "port (default range 30000-32767). External traffic can reach "
                "the service via `<NodeIP>:<NodePort>`."
            ),
            distractors={
                "A": "ClusterIP is internal only — accessible within the cluster, not externally.",
                "C": "LoadBalancer provisions a cloud load balancer, not a static node port.",
                "D": "ExternalName maps a service to a DNS name, not a port.",
            },
            mcq_type="conceptual",
        ),
    ]

    return TopicSection(
        title="Basic Kubernetes Concepts",
        difficulty="Mid-Level",
        explanation=explanation,
        examples=examples,
        practice=mcqs,
        key_takeaways=[
            "Pod = smallest unit (one or more containers); Deployment = manages pod replicas.",
            "Service types: ClusterIP (internal), NodePort (external via node port), LoadBalancer (cloud).",
            "`kubectl get`, `kubectl describe`, `kubectl logs` are your daily K8s commands.",
            "`kubectl apply -f` applies YAML manifests — the declarative way to manage resources.",
            "NVIDIA uses K8s with the GPU device plugin for scheduling GPU workloads.",
        ],
    )


def _pxe_boot_overview() -> TopicSection:
    explanation = (
        "### PXE Boot Overview (NVIDIA-Relevant)\n\n"
        "**PXE (Preboot Execution Environment)** allows a computer to boot "
        "from the network instead of a local disk. It's widely used for:\n"
        "- Automated OS installation across server fleets\n"
        "- Diskless workstations\n"
        "- System recovery and diagnostics\n\n"
        "**PXE boot flow:**\n"
        "1. Client powers on and sends a DHCP Discover broadcast.\n"
        "2. DHCP server responds with an IP address AND the PXE boot server "
        "address + boot filename.\n"
        "3. Client downloads the boot loader (e.g., `pxelinux.0`) via **TFTP** "
        "(Trivial File Transfer Protocol).\n"
        "4. Boot loader downloads the kernel and initrd from the TFTP server.\n"
        "5. Kernel boots and may fetch additional files (kickstart/preseed) "
        "via HTTP/NFS for automated installation.\n\n"
        "**Key components:**\n"
        "- **DHCP server** — assigns IP and points to TFTP server\n"
        "- **TFTP server** — serves the boot loader and kernel\n"
        "- **HTTP/NFS server** — serves the OS installation files\n"
        "- **Kickstart (RHEL) / Preseed (Debian)** — automated install config\n\n"
        "**NVIDIA context:** PXE boot is used to provision bare-metal GPU "
        "servers at scale, deploy custom OS images with NVIDIA drivers, and "
        "manage server fleets in data centers."
    )

    examples = [
        (
            "# --- PXE boot configuration examples ---\n"
            "import textwrap\n\n"
            "pxe_config = textwrap.dedent('''\n"
            "    # --- DHCP server config (ISC DHCP) ---\n"
            "    # /etc/dhcp/dhcpd.conf\n"
            "    subnet 10.0.1.0 netmask 255.255.255.0 {\n"
            "        range 10.0.1.100 10.0.1.200;\n"
            "        option routers 10.0.1.1;\n"
            "        option domain-name-servers 10.0.1.1;\n"
            "        # PXE boot options\n"
            "        next-server 10.0.1.10;          # TFTP server IP\n"
            "        filename \"pxelinux.0\";           # Boot loader file\n"
            "    }\n\n"
            "    # --- PXE menu config ---\n"
            "    # /tftpboot/pxelinux.cfg/default\n"
            "    DEFAULT menu.c32\n"
            "    PROMPT 0\n"
            "    TIMEOUT 300\n"
            "    MENU TITLE PXE Boot Menu\n\n"
            "    LABEL ubuntu\n"
            "        MENU LABEL Install Ubuntu 22.04\n"
            "        KERNEL ubuntu/vmlinuz\n"
            "        APPEND initrd=ubuntu/initrd.gz auto=true url=http://10.0.1.10/preseed.cfg\n\n"
            "    LABEL centos\n"
            "        MENU LABEL Install CentOS 9\n"
            "        KERNEL centos/vmlinuz\n"
            "        APPEND initrd=centos/initrd.img ks=http://10.0.1.10/kickstart.cfg\n\n"
            "    # --- PXE boot flow summary ---\n"
            "    # 1. Client: DHCP Discover (broadcast)\n"
            "    # 2. DHCP Server: Offer IP + next-server=10.0.1.10, filename=pxelinux.0\n"
            "    # 3. Client: TFTP GET pxelinux.0 from 10.0.1.10\n"
            "    # 4. Client: TFTP GET pxelinux.cfg/default (menu config)\n"
            "    # 5. Client: TFTP GET kernel + initrd\n"
            "    # 6. Kernel boots, fetches kickstart/preseed via HTTP\n"
            "    # 7. Automated OS installation begins\n"
            "''')\n"
            "print(pxe_config)"
        ),
    ]

    mcqs = [
        MCQ(
            question="In a PXE boot process, which protocol is used to transfer the initial boot loader to the client?",
            options={
                "A": "HTTP",
                "B": "FTP",
                "C": "TFTP",
                "D": "NFS",
            },
            correct="C",
            explanation=(
                "TFTP (Trivial File Transfer Protocol) is used for the initial "
                "boot loader transfer in PXE. It's a simple, lightweight "
                "protocol that works well in the pre-OS boot environment where "
                "a full TCP/IP stack isn't available yet."
            ),
            distractors={
                "A": "HTTP may be used later for kickstart/preseed files, but not for the initial boot loader.",
                "B": "FTP is too complex for the PXE boot environment.",
                "D": "NFS may serve installation files later, but TFTP handles the initial boot loader.",
            },
            mcq_type="conceptual",
        ),
    ]

    return TopicSection(
        title="PXE Boot Overview",
        difficulty="Mid-Level",
        explanation=explanation,
        examples=examples,
        practice=mcqs,
        key_takeaways=[
            "PXE boot flow: DHCP → TFTP (boot loader) → TFTP (kernel) → HTTP/NFS (install files).",
            "DHCP `next-server` and `filename` directives point the client to the TFTP server.",
            "TFTP is used for the initial boot loader; HTTP/NFS for larger installation files.",
            "Kickstart (RHEL) and Preseed (Debian) automate unattended OS installations.",
            "PXE is essential for provisioning bare-metal servers at scale in data centers.",
        ],
    )
